# Generated by Django 3.2.3 on 2021-06-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('time', models.DateTimeField()),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
